import type { MainApiAsync } from "backend-app";
import { BrowserWindow, IpcMainEvent } from "electron";

// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Webpack
// plugin that tells the Electron app where to look for the Webpack-bundled app code (depending on
// whether you're running in development or production).

declare const MAIN_WINDOW_WEBPACK_ENTRY: string;
declare const MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY: string;

// Create the browser window.
export const createBrowserWindow = (): BrowserWindow =>
  new BrowserWindow({
    show: false,
    webPreferences: {
      preload: MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY,
    },
  });

// and load the index.html of the app.
export const loadURL = async (window: BrowserWindow): Promise<void> => {
  await window.loadURL(MAIN_WINDOW_WEBPACK_ENTRY);
  window.maximize();
};

export const appWindows = (() => {
  type AppWindow = { mainApi: MainApiAsync; window: BrowserWindow };
  const instances: { [index: number]: AppWindow } = {};

  const find = (event: IpcMainEvent): MainApiAsync | undefined => instances[event.sender.id]?.mainApi;
  const add = (mainApi: MainApiAsync, window: BrowserWindow): void => {
    const id = window.webContents.id;
    instances[id] = { mainApi, window };
    window.on("closed", () => {
      delete instances[id];
    });
  };
  const closeAll = (mainWindow: BrowserWindow): void =>
    Object.entries(instances).forEach(([index, appWindow]) => {
      if (appWindow.window !== mainWindow) appWindow.window.close();
      delete instances[+index];
    });

  return { find, add, closeAll };
})();
