using Microsoft.Win32;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Reflection.PortableExecutable;
using System.Runtime.Versioning;
using System.Text.Json;

namespace Core.Loader
{
    // these methods are only used by AssemblyResolver
    // their implementation does not depend on Mono.Cecil APIs
    internal static class AssemblyResolverPaths
    {
        internal static string GetDirectoryName(string path) => Path.GetDirectoryName(path).NotNull();

        internal static bool IsCompatibleWith(FrameworkName exe, FrameworkName lib)
        {
            if (lib.IsStandard())
            {
                // a .NET Standard library is compatible with any .NET implementation that supports that version of .NET Standard
                if (!exe.IsStandard())
                {
                    return lib.Version == new Version(2, 0);
                }
                else if (exe.IsCore())
                {
                    return true;
                }
                else
                {
                    throw new Exception($"Unexpected Exe {exe}");
                }
            }
            if (exe.IsFramework() && lib.IsFramework() || exe.IsCore() && lib.IsCore())
            {
                return lib.Version <= exe.Version;
            }
            return false;
        }

        internal static string? GetMicrosoftDirectory(string assemblyPath, FrameworkName frameworkName) => frameworkName.IsCore()
                ? GetCoreDirectory(assemblyPath, frameworkName)
                : frameworkName.IsFramework()
                ? GetFrameworkDirectory(frameworkName.Version)
                : throw new Exception($"Unexpected FrameworkName {frameworkName.FullName}");

        static string? GetCoreDirectory(string assemblyPath, FrameworkName frameworkName)
        {
            var runtimeTarget = GetRuntimeTarget(assemblyPath, frameworkName);
            if (runtimeTarget == null)
            {
                return null;
            }
            return GetCoreDirectory(runtimeTarget);
        }

        private static FrameworkName? GetRuntimeTarget(string assemblyPath, FrameworkName frameworkName)
        {
            /*
             * format of config file is document here:
             * 
             * - https://github.com/dotnet/sdk/blob/main/documentation/specs/runtime-configuration-file.md
             * 
             * The runtimeconfig.json specifies the framework on which the application wants to run and is user-editable.
             * The deps.json specifies the framework on which application will actually run and is generated by the SDK for that machine.
             * 
             * The runtimeconfig.json file can specify several frameworks.
             * The deps.json specifies a single framework.
             */
            var hostfxrPath = Path.Join(GetDirectoryName(assemblyPath), "hostfxr.dll");
            if (File.Exists(hostfxrPath))
            {
                // this is a self-contained app, so no shared framework is used
                return null;
            }

            var depsPath = Path.ChangeExtension(assemblyPath, ".deps.json");
            if (!File.Exists(depsPath))
            {
                return frameworkName;
            }

            using var doc = JsonDocument.Parse(File.ReadAllText(depsPath));
            var root = doc.RootElement;
            var name = root.GetProperty("runtimeTarget").GetProperty("name").GetString().NotNull();
            return new FrameworkName(name);
        }

        private static string GetCoreDirectory(FrameworkName frameworkName)
        {
            var dotnetSharedRoot = Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.ProgramFiles), "dotnet", "shared");
            var subdirectory = frameworkName.Identifier == ".NETCoreApp" ? "Microsoft.NetCore.App" : frameworkName.Identifier;
            var frameworkRoot = Path.Combine(dotnetSharedRoot, subdirectory);

            if (!Directory.Exists(frameworkRoot))
            {
                throw new Exception($"Shared framework not found: {frameworkName.Identifier}");
            }

            var versions = GetVersionsFromSubdirectories(frameworkRoot);
            var matching = versions.Where(v => v.Major == frameworkName.Version.Major && v.Minor == frameworkName.Version.Minor).ToArray();

            if (matching.Length == 0)
            {
                throw new Exception($"No installed shared framework found matching {frameworkName.Identifier} {frameworkName.Version}");
            }

            var highest = matching.Max();
            return GetSubdirectoryFromVersion(frameworkRoot, highest!);
        }

        static string GetFrameworkDirectory(Version frameworkVersion)
        {
            var frameworkRoot = Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.Windows), "Microsoft.NET", "Framework");
            var versions = GetVersionsFromSubdirectories(frameworkRoot);
            var matching = versions.SingleOrDefault(v => v.Major == frameworkVersion.Major);
            if (matching == null)
            {
                throw new Exception($"No installed .NET Framework found matching {frameworkVersion}");
            }
            // read HKLM:\SOFTWARE\Microsoft\NET Framework Setup\NDP\v4\Full
#pragma warning disable CA1416 // Validate platform compatibility
            using var key = Registry.LocalMachine.OpenSubKey("SOFTWARE\\Microsoft\\NET Framework Setup\\NDP\\v4\\Full");
            var supported = key?.GetValue("Version") as string;
            if (supported == null)
            {
                throw new Exception($"Could not read .NET Framework version from registry");
            }
            var supportedVersion = Version.Parse(supported);
            if (supportedVersion < frameworkVersion)
            {
                throw new Exception($".NET Framework version {frameworkVersion} required, but only version {supportedVersion} is installed");
            }
#pragma warning restore CA1416 // Validate platform compatibility
            return GetSubdirectoryFromVersion(frameworkRoot, matching);
        }

        private static Version[] GetVersionsFromSubdirectories(string directory) => Directory.GetDirectories(directory)
            .Select(dir => Path.GetFileName(dir))
            .Select(name => Version.Parse(name)).ToArray();

        private static string GetSubdirectoryFromVersion(string root, Version version)
        {
            var subdirectory = Path.Combine(root, version.ToString());
            if (!Directory.Exists(subdirectory))
            {
                throw new Exception($"No directory found for version {version} in {root}");
            }
            return subdirectory;
        }

        private static bool IsFramework(this FrameworkName frameworkName) => frameworkName.Identifier.Equals(".NETFramework", StringComparison.OrdinalIgnoreCase);
        private static bool IsCore(this FrameworkName frameworkName) => frameworkName.Identifier.Equals(".NETCoreApp", StringComparison.OrdinalIgnoreCase);
        private static bool IsStandard(this FrameworkName frameworkName) => frameworkName.Identifier.Equals(".NETStandard", StringComparison.OrdinalIgnoreCase);
    }
}
